### PR TITLE
Add property for ignoring touch dragging on the slider bar

### PR DESCRIPTION
**Pull request by NovapaX**
Only a tap and a mousedown on the bar should alter the knob-position.
Fixes https://github.com/PolymerElements/paper-slider/issues/178

### CODE REVIEW

**Comment by NovapaX** [comment]
CLA signed

**Comment by NovapaX** [comment]
This is a bit more complicated than initially thought.
To accomplish this in a clean way there should be a mousetrack event. So we could just reuse the onTrack function and set `on-mousetrack="_onTrack"` on the slider bar.
Or someone must have another idea how to accomplish the following behaviour:
- mouse click on the bar sets position and starts dragging
- touchmove on the bar does nothing
- touch tap on the bar sets position

**Comment by NovapaX** [comment]
oh wow... looks like I can't test the click event.
created a seperate PR for that: https://github.com/PolymerElements/iron-test-helpers/pull/93

**Comment by e111077** [comment]
This is a breaking change. Can you please hide this feature under a flag? I'm guessing you can do this in connected callback:

```
properties = {
  __boundListenFn:  {
    type: Function
  },
  __eventType:  {
    type: string,
    value: 'down'
  },
  /**
   * insert closure doc
   */
  ignoreBarClicks: {
    type: Boolean,
    value: false
  }
}

connectedCallback() {
  ...
  if (this.ignoreBarClicks) {
    // or however you want to implement this
    this.__eventType = 'click';
    this.__boundListenFn = this._barclick.bind(this);
  } else {
    this.__eventType = 'down';
    this.__boundListenFn = this._bardown.bind(this);
  }

  this.$.slderBar.addEventListener(this.__eventType, this.__boundListenFn);
}

disconnectedCallback() {
  ...
  this.$.slderBar.removeEventListener(this.__eventType, this.__boundListenFn);
}
```

I'll see if i can figure out what's going on with mockInteractions

**Comment by NovapaX** [comment]
I came up with a working solution that ignores tracking of touches on the slider bar, but allows tapping on the slider bar to set the knob position.
Also was able to enable it all throught the `on-[event]` attributes so no need to manually set and tear down eventListeners.

**Comment by e111077** [comment]
Hmm, I think this will work. I have to run it through an internal suite of tests to see if it breaks anything; we may be able to push this through as a bug fix

**Comment by e111077** [comment]
This PR slipped through the cracks. Will prioritize internal testing

**Comment by e111077** [comment]
All tests pass. You're golden!

**Comment by NovapaX** [comment]
Great! Thanks for your help!

**Comment by NovapaX** [comment]
any idea on whether (and when) this can get pushed into a release?

**Comment by e111077** [comment]
We've been moving to a weekly release committee / schedule. Expect to see an update on Friday

**Comment by e111077** [comment]
Released a [`v2.0.5`](https://github.com/PolymerElements/paper-slider/releases/tag/v2.0.5)

**Pull request merged**
