### PR TITLE
move the events to the bottom of the file so the doc shows up correctly.

### LINKED ISSUE #28: Wrong doc shows up for paper-slider
The `Documentation` shows the events instead of the actual summary.

screen shot 2015-06-18 at 3 36 56 pm

### PR DESCRIPTION
**Pull request by frankiefu**
fixes #28 

After the fix:
screen shot 2015-06-18 at 3 41 28 pm

### CODE REVIEW

**Comment by blasten** [comment]
\cc @garlicnation  Is there a reason why the order of this comment should matter?

**Comment by garlicnation** [comment]
The docs look like element docs to me when they're before Polymer.

**Comment by frankiefu** [comment]
@garlicnation The doc displays the events at the top instead of the summary.  Also the demo button is missing.

screen shot 2015-06-19 at 8 50 48 am

**Comment by blasten** [comment]
LGTM :+1:

**Pull request merged**
