### PR TITLE
Update with --calculated-paper-slider-height

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by keanulee** [comment]
@abdonrd Is the point of this PR to only have the default 2px in once place? I don't know if I like this pattern of introducing a new custom property just to do this.

**Comment by abdonrd** [comment]
@keanulee yes, like the paper-checkbox: https://github.com/PolymerElements/paper-checkbox/blob/master/paper-checkbox.html#L60 :)

**Comment by keanulee** [comment]
Ah, I didn't know about that. Makes sense, LGTM

**Comment by abdonrd** [comment]
Thanks @keanulee! 😄

**Pull request merged**
