### PR TITLE
Fix flaky test

### PR DESCRIPTION
**Pull request by keanulee**

### CODE REVIEW

**Comment by keanulee** [comment]
Well, it's fixed for IE. Firefox is being weird though :(

**Comment by notwaldorf** [comment]
This seems like it's failing on all the things, FF and Chrome :(

**Comment by blasten** [comment]
nit: you might consider adding an event listener for keydown and checking the state in the next tick. That way you could avoid potential issues like what if the keydown event fires after the callback is called. Is this the test that is failing?

**Comment by keanulee** [comment]
Fixes #117 as well.

cc @notwaldorf @blasten

**Comment by blasten** [comment]
@keanulee this is awesome!

**Pull request merged**
