### PR TITLE
Set height for paper-progress

### PR DESCRIPTION
**Pull request by blasten**
This is required for https://github.com/PolymerElements/paper-progress/issues/18

### CODE REVIEW

**Comment by devinivy** [comment]
This doesn't seem to fix the issue– the 8px margin and padding are responsible for the progress bar's bulk.

**Comment by blasten** [comment]
@devinivy what is the issue? This is just the height.

**Comment by devinivy** [comment]
Sorry– should have been more specific.  The screenshot of 1.0.3 in https://github.com/PolymerElements/paper-progress/issues/18 is still essentially what you'd see in 1.0.5.  I'm running the 1.0.5 demo right now and the slider still appears incorrectly.  It's corrected by removing the 8px margin and padding from `paper-progress`.

**Edit**
Ah, I think I understand– there are still more fixes in the works to correct https://github.com/PolymerElements/paper-progress/issues/18?  Though it is closed.  I guess I'm a little confused.  Sorry for hasslin'!

**Comment by blasten** [comment]
yes, that issue should be fixed by now.

**Pull request merged**
