### PR TITLE
Notify `immediateValue`

### PR DESCRIPTION
**Pull request by blasten**
Requested via https://github.com/PolymerElements/paper-slider/issues/60

### CODE REVIEW

**Comment by samccone** [comment]
is there a test we can put into place here?

**Comment by blasten** [comment]
@samccone it could, but `notify` is tested in Polymer directly https://github.com/Polymer/polymer/blob/83cce66ece1f264e86d5bd031a3ae2719b731b90/test/unit/notify-path-elements.html what do you think?

**Comment by samccone** [comment]
My thinking was that the test would be to enforce this `interface` and prevent someone in the future from accidentally removing in.

**Comment by blasten** [comment]
ok that's fair. I will add one.

**Comment by samccone** [comment]
awesome :palm_tree: :two_hearts:

**Comment by blasten** [comment]
tests added 🎉

**Comment by samccone** [comment]
@blasten did you forget to push¿

**Comment by blasten** [comment]
@samccone yah. it's there now :)

**Comment by frankiefu** [comment]
LGTM

**Comment by samccone** [comment]
:clap: :a: :heavy_plus_sign:

**Pull request merged**
